### ISSUE TITLE
Man, what the fuck are you trying to make? please provide a description atleast.

### ISSUE THREAD

**Issue by ghost** [ms-jpq/std2#1]

**Comment by ms-jpq** [comment]
can you please not be so rude?

this is a base library that im going to be using for my other python projects. I am still working on it so not having a README is par for the course

**Comment by ghost** [comment]
Bruh, that's just a bruh moment right there. You should always provide a description for the passers by and how hard is it to add
'this is a base library that im going to be using for my other python projects' in your readme and if you added how to install it via pip  then you are intending on other people to use it. Adding a install link And not saying what it is just weird and creepy.
